#!/usr/bin/env bash
# ── generate-tfvars.sh ────────────────────────────────────────────────────────
# Reads an .env file and writes infra/terraform/envs/<tf-env>/terraform.tfvars,
# so non-reuse TF inputs (tenant_id, container_image, sku knobs, …) live in
# the same env file as everything else. Re-runnable / idempotent.
#
# Usage:
#   ./infra/scripts/generate-tfvars.sh .env_qa test
#
# Source-of-truth keys in the env file (all optional unless noted):
#   TF_PROJECT, TF_ENVIRONMENT, TF_LOCATION
#   TF_TENANT_ID                  (required if not provided via tfvars/CLI)
#   TF_PUBLISHER_EMAIL            (required by APIM module schema, even when disabled)
#   TF_CONTAINER_IMAGE
#   TF_HOST_CHOICE                (webapp_container | container_apps)
#   TF_APP_SERVICE_SKU, TF_FUNCTIONS_SKU, TF_SERVICE_BUS_SKU, TF_SB_QUEUE_NAME
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ENV_FILE="${1:?Usage: generate-tfvars.sh <env-file> <tf-env>}"
TF_ENV="${2:?Usage: generate-tfvars.sh <env-file> <tf-env>}"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE_PATH="$REPO_ROOT/$ENV_FILE"
TF_DIR="$REPO_ROOT/infra/terraform/envs/$TF_ENV"
OUT="$TF_DIR/terraform.tfvars"

[[ -f "$ENV_FILE_PATH" ]] || { echo "ERROR: $ENV_FILE_PATH not found" >&2; exit 1; }
[[ -d "$TF_DIR"        ]] || { echo "ERROR: $TF_DIR not found"        >&2; exit 1; }

# ── Parse env file ────────────────────────────────────────────────────────────
declare -A E
while IFS='=' read -r k v; do
  k="${k// /}"
  [[ -z "$k" || "$k" == \#* ]] && continue
  v="${v%$'\r'}"                 # strip CR (Windows)
  v="${v%%#*}"                   # strip trailing inline comments
  v="$(echo "$v" | sed 's/[[:space:]]*$//')"
  E["$k"]="$v"
done < "$ENV_FILE_PATH"

g() {
  local v="${E[$1]:-${2:-}}"
  # treat angle-bracket placeholders (e.g. <tenant-guid>) as unset
  [[ "$v" == *"<"*">"* ]] && v=""
  echo "$v"
}

# HCL string escaper: backslash + double-quote, wrap in "..."
hcl() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '"%s"' "$s"
}

# ── Emit terraform.tfvars ─────────────────────────────────────────────────────
{
  echo "# Auto-generated by infra/scripts/generate-tfvars.sh from $ENV_FILE"
  echo "# Do NOT edit by hand; change the env file and re-run the script."
  echo ""
  printf 'project             = %s\n' "$(hcl "$(g TF_PROJECT awr)")"
  printf 'environment         = %s\n' "$(hcl "$(g TF_ENVIRONMENT "$TF_ENV")")"
  printf 'location            = %s\n' "$(hcl "$(g TF_LOCATION eastus2)")"
  printf 'tenant_id           = %s\n' "$(hcl "$(g TF_TENANT_ID "$(g AAD_TENANT_ID '')")")"
  printf 'publisher_email     = %s\n' "$(hcl "$(g TF_PUBLISHER_EMAIL platform-team@example.com)")"
  printf 'container_image     = %s\n' "$(hcl "$(g TF_CONTAINER_IMAGE ghcr.io/placeholder/awr-platform-api:latest)")"
  printf 'host_choice         = %s\n' "$(hcl "$(g TF_HOST_CHOICE webapp_container)")"
  printf 'app_service_sku     = %s\n' "$(hcl "$(g TF_APP_SERVICE_SKU B2)")"
  printf 'functions_sku       = %s\n' "$(hcl "$(g TF_FUNCTIONS_SKU Y1)")"
  printf 'service_bus_sku     = %s\n' "$(hcl "$(g TF_SERVICE_BUS_SKU Standard)")"
  printf 'sb_queue_name       = %s\n' "$(hcl "$(g TF_SB_QUEUE_NAME engine-runs)")"
} > "$OUT"

# ── Sanity check: warn on empty required values or placeholders ───────────────
warn=0
check_required() {
  local key="$1" fallback_key="${2:-}"
  local val="$(g "$key" '')"
  if [[ -z "$val" && -n "$fallback_key" ]]; then
    val="$(g "$fallback_key" '')"
  fi
  if [[ -z "$val" || "$val" == *"<"*">"* ]]; then
    echo "INFO: $key not set in $ENV_FILE — only required if provisioning the related resource." >&2
  fi
}
check_required TF_TENANT_ID AAD_TENANT_ID

echo "Wrote $OUT"
[[ $warn -eq 0 ]] || exit 0
